/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Aircraft {
    id: bigint;
    totalHours: bigint;
    name: string;
    hourLog: Array<HourLogEntry>;
}
export interface Entity {
    id: bigint;
    name: string;
}
export type Time = bigint;
export interface HourLogEntry {
    hours: bigint;
    date: Time;
}
export interface DashboardStats {
    aircraftUtilization: Array<[string, bigint]>;
    monthlyTotalFlights: bigint;
    dailyTotalHours: bigint;
    monthlyTotalHours: bigint;
    recentFlights: Array<FlightEntry>;
    dailyTotalFlights: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
}
export interface FlightEntry {
    duration: bigint;
    instructor: string;
    date: Time;
    exercise: string;
    flightType: FlightType;
    aircraft: string;
    student: string;
    takeoffTime: string;
    landingTime: string;
    landingType: LandingType;
    landingCount: bigint;
}
export enum FlightType {
    dual = "dual",
    solo = "solo"
}
export enum LandingType {
    day = "day",
    night = "night"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addEntity(listType: string, name: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    computeRunningTotalHours(aircraftId: bigint): Promise<bigint>;
    deleteEntity(listType: string, id: bigint): Promise<void>;
    editEntity(listType: string, id: bigint, newName: string): Promise<void>;
    filterFlights(month: string, student: string, aircraftFilter: string): Promise<Array<FlightEntry>>;
    getAircraftHourLog(aircraftId: bigint): Promise<Array<HourLogEntry>>;
    getAircraftList(): Promise<Array<Aircraft>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getEntities(listType: string): Promise<Array<Entity>>;
    getFlights(): Promise<Array<FlightEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    logFlight(entry: FlightEntry): Promise<void>;
    recordAircraftHours(aircraftId: bigint, date: Time, hours: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { DashboardStats as _DashboardStats, FlightEntry as _FlightEntry, FlightType as _FlightType, LandingType as _LandingType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEntity(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEntity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEntity(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async computeRunningTotalHours(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.computeRunningTotalHours(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeRunningTotalHours(arg0);
            return result;
        }
    }
    async deleteEntity(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEntity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEntity(arg0, arg1);
            return result;
        }
    }
    async editEntity(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editEntity(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editEntity(arg0, arg1, arg2);
            return result;
        }
    }
    async filterFlights(arg0: string, arg1: string, arg2: string): Promise<Array<FlightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterFlights(arg0, arg1, arg2);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterFlights(arg0, arg1, arg2);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAircraftHourLog(arg0: bigint): Promise<Array<HourLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAircraftHourLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAircraftHourLog(arg0);
            return result;
        }
    }
    async getAircraftList(): Promise<Array<Aircraft>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAircraftList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAircraftList();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return from_candid_DashboardStats_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return from_candid_DashboardStats_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntities(arg0: string): Promise<Array<Entity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntities(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntities(arg0);
            return result;
        }
    }
    async getFlights(): Promise<Array<FlightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlights();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlights();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logFlight(arg0: FlightEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logFlight(to_candid_FlightEntry_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logFlight(to_candid_FlightEntry_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async recordAircraftHours(arg0: bigint, arg1: Time, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAircraftHours(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAircraftHours(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_DashboardStats_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardStats): DashboardStats {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_FlightEntry_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlightEntry): FlightEntry {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_FlightType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlightType): FlightType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_LandingType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LandingType): LandingType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aircraftUtilization: Array<[string, bigint]>;
    monthlyTotalFlights: bigint;
    dailyTotalHours: bigint;
    monthlyTotalHours: bigint;
    recentFlights: Array<_FlightEntry>;
    dailyTotalFlights: bigint;
}): {
    aircraftUtilization: Array<[string, bigint]>;
    monthlyTotalFlights: bigint;
    dailyTotalHours: bigint;
    monthlyTotalHours: bigint;
    recentFlights: Array<FlightEntry>;
    dailyTotalFlights: bigint;
} {
    return {
        aircraftUtilization: value.aircraftUtilization,
        monthlyTotalFlights: value.monthlyTotalFlights,
        dailyTotalHours: value.dailyTotalHours,
        monthlyTotalHours: value.monthlyTotalHours,
        recentFlights: from_candid_vec_n3(_uploadFile, _downloadFile, value.recentFlights),
        dailyTotalFlights: value.dailyTotalFlights
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: bigint;
    instructor: string;
    date: _Time;
    exercise: string;
    flightType: _FlightType;
    aircraft: string;
    student: string;
    takeoffTime: string;
    landingTime: string;
    landingType: _LandingType;
    landingCount: bigint;
}): {
    duration: bigint;
    instructor: string;
    date: Time;
    exercise: string;
    flightType: FlightType;
    aircraft: string;
    student: string;
    takeoffTime: string;
    landingTime: string;
    landingType: LandingType;
    landingCount: bigint;
} {
    return {
        duration: value.duration,
        instructor: value.instructor,
        date: value.date,
        exercise: value.exercise,
        flightType: from_candid_FlightType_n6(_uploadFile, _downloadFile, value.flightType),
        aircraft: value.aircraft,
        student: value.student,
        takeoffTime: value.takeoffTime,
        landingTime: value.landingTime,
        landingType: from_candid_LandingType_n8(_uploadFile, _downloadFile, value.landingType),
        landingCount: value.landingCount
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dual: null;
} | {
    solo: null;
}): FlightType {
    return "dual" in value ? FlightType.dual : "solo" in value ? FlightType.solo : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: null;
} | {
    night: null;
}): LandingType {
    return "day" in value ? LandingType.day : "night" in value ? LandingType.night : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FlightEntry>): Array<FlightEntry> {
    return value.map((x)=>from_candid_FlightEntry_n4(_uploadFile, _downloadFile, x));
}
function to_candid_FlightEntry_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlightEntry): _FlightEntry {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_FlightType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlightType): _FlightType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_LandingType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LandingType): _LandingType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: bigint;
    instructor: string;
    date: Time;
    exercise: string;
    flightType: FlightType;
    aircraft: string;
    student: string;
    takeoffTime: string;
    landingTime: string;
    landingType: LandingType;
    landingCount: bigint;
}): {
    duration: bigint;
    instructor: string;
    date: _Time;
    exercise: string;
    flightType: _FlightType;
    aircraft: string;
    student: string;
    takeoffTime: string;
    landingTime: string;
    landingType: _LandingType;
    landingCount: bigint;
} {
    return {
        duration: value.duration,
        instructor: value.instructor,
        date: value.date,
        exercise: value.exercise,
        flightType: to_candid_FlightType_n17(_uploadFile, _downloadFile, value.flightType),
        aircraft: value.aircraft,
        student: value.student,
        takeoffTime: value.takeoffTime,
        landingTime: value.landingTime,
        landingType: to_candid_LandingType_n19(_uploadFile, _downloadFile, value.landingType),
        landingCount: value.landingCount
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlightType): {
    dual: null;
} | {
    solo: null;
} {
    return value == FlightType.dual ? {
        dual: null
    } : value == FlightType.solo ? {
        solo: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LandingType): {
    day: null;
} | {
    night: null;
} {
    return value == LandingType.day ? {
        day: null
    } : value == LandingType.night ? {
        night: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
