/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const FlightType = IDL.Variant({ 'dual' : IDL.Null, 'solo' : IDL.Null });
export const LandingType = IDL.Variant({
  'day' : IDL.Null,
  'night' : IDL.Null,
});
export const FlightEntry = IDL.Record({
  'duration' : IDL.Nat,
  'instructor' : IDL.Text,
  'date' : Time,
  'exercise' : IDL.Text,
  'flightType' : FlightType,
  'aircraft' : IDL.Text,
  'student' : IDL.Text,
  'takeoffTime' : IDL.Text,
  'landingTime' : IDL.Text,
  'landingType' : LandingType,
  'landingCount' : IDL.Nat,
});
export const HourLogEntry = IDL.Record({ 'hours' : IDL.Nat, 'date' : Time });
export const Aircraft = IDL.Record({
  'id' : IDL.Nat,
  'totalHours' : IDL.Nat,
  'name' : IDL.Text,
  'hourLog' : IDL.Vec(HourLogEntry),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'aircraftUtilization' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'monthlyTotalFlights' : IDL.Nat,
  'dailyTotalHours' : IDL.Nat,
  'monthlyTotalHours' : IDL.Nat,
  'recentFlights' : IDL.Vec(FlightEntry),
  'dailyTotalFlights' : IDL.Nat,
});
export const Entity = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEntity' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'computeRunningTotalHours' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'deleteEntity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'editEntity' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'filterFlights' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(FlightEntry)],
      ['query'],
    ),
  'getAircraftHourLog' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(HourLogEntry)],
      ['query'],
    ),
  'getAircraftList' : IDL.Func([], [IDL.Vec(Aircraft)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getEntities' : IDL.Func([IDL.Text], [IDL.Vec(Entity)], ['query']),
  'getFlights' : IDL.Func([], [IDL.Vec(FlightEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logFlight' : IDL.Func([FlightEntry], [], []),
  'recordAircraftHours' : IDL.Func([IDL.Nat, Time, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const FlightType = IDL.Variant({ 'dual' : IDL.Null, 'solo' : IDL.Null });
  const LandingType = IDL.Variant({ 'day' : IDL.Null, 'night' : IDL.Null });
  const FlightEntry = IDL.Record({
    'duration' : IDL.Nat,
    'instructor' : IDL.Text,
    'date' : Time,
    'exercise' : IDL.Text,
    'flightType' : FlightType,
    'aircraft' : IDL.Text,
    'student' : IDL.Text,
    'takeoffTime' : IDL.Text,
    'landingTime' : IDL.Text,
    'landingType' : LandingType,
    'landingCount' : IDL.Nat,
  });
  const HourLogEntry = IDL.Record({ 'hours' : IDL.Nat, 'date' : Time });
  const Aircraft = IDL.Record({
    'id' : IDL.Nat,
    'totalHours' : IDL.Nat,
    'name' : IDL.Text,
    'hourLog' : IDL.Vec(HourLogEntry),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const DashboardStats = IDL.Record({
    'aircraftUtilization' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'monthlyTotalFlights' : IDL.Nat,
    'dailyTotalHours' : IDL.Nat,
    'monthlyTotalHours' : IDL.Nat,
    'recentFlights' : IDL.Vec(FlightEntry),
    'dailyTotalFlights' : IDL.Nat,
  });
  const Entity = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEntity' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'computeRunningTotalHours' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'deleteEntity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'editEntity' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'filterFlights' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(FlightEntry)],
        ['query'],
      ),
    'getAircraftHourLog' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(HourLogEntry)],
        ['query'],
      ),
    'getAircraftList' : IDL.Func([], [IDL.Vec(Aircraft)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getEntities' : IDL.Func([IDL.Text], [IDL.Vec(Entity)], ['query']),
    'getFlights' : IDL.Func([], [IDL.Vec(FlightEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logFlight' : IDL.Func([FlightEntry], [], []),
    'recordAircraftHours' : IDL.Func([IDL.Nat, Time, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };