/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AircraftInput { 'totalHours' : bigint, 'name' : string }
export interface DashboardStats {
  'aircraftUtilization' : Array<[string, bigint]>,
  'monthlyTotalFlights' : bigint,
  'dailyTotalHours' : bigint,
  'monthlyTotalHours' : bigint,
  'recentFlights' : Array<FlightEntry>,
  'dailyTotalFlights' : bigint,
}
export interface Entity { 'id' : bigint, 'name' : string }
export interface FlightEntry {
  'duration' : bigint,
  'instructor' : string,
  'date' : Time,
  'exercise' : string,
  'flightType' : FlightType,
  'aircraft' : string,
  'student' : string,
  'takeoffTime' : string,
  'landingTime' : string,
  'landingType' : LandingType,
  'landingCount' : bigint,
}
export type FlightType = { 'dual' : null } |
  { 'solo' : null };
export type LandingType = { 'day' : null } |
  { 'night' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEntity' : ActorMethod<[string, string], undefined>,
  'addFlightEntry' : ActorMethod<
    [
      Time,
      string,
      string,
      string,
      string,
      FlightType,
      string,
      string,
      bigint,
      LandingType,
      bigint,
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAircraft' : ActorMethod<[bigint], undefined>,
  'deleteEntity' : ActorMethod<[string, bigint], undefined>,
  'editEntity' : ActorMethod<[string, bigint, string], undefined>,
  'filterFlights' : ActorMethod<[string, string, string], Array<FlightEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getEntities' : ActorMethod<[string], Array<Entity>>,
  'getFlights' : ActorMethod<[], Array<FlightEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordDailyHours' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAircraft' : ActorMethod<[bigint, AircraftInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];